version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ../backend
      args:
        MODE: production
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always